### ISSUE TITLE
Unable to sync data due to not null constraints 

### ISSUE THREAD

**Issue by BuddhiAbeyratneAL** [oscarychen/drf-stripe-subscription#29]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/87055020/219571919-9f6a27c7-24fc-46e2-888f-c36f63f99b49.png">

**Comment by oscarychen** [comment]
Make sure you have a price for each product.
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/22269057/221439191-9ac7985e-c02d-4b95-bc2d-3323874893b7.png">

**Comment by BuddhiAbeyratne** [comment]
null and 0 are valid numbers coming from Stripe @oscarychen

**Comment by oscarychen** [comment]
Just curious, how are you using stripe where you have null amount for price?

**Comment by BuddhiAbeyratneAL** [comment]
hey 
a few issues I've fixed so far 

- Stripe users can have multiple subscriptions according to api (Specially if you are using payment links) stripe doesn't have unicity 
- a user can buy a subscription without being on system 
- the system for some reason goes an tries to update a users email in revers ( this is not ideal and is potentially a things to remember security wise )

I have fixed all of this in my repo but my commits are all over the place and idk if you'd like a bad commit log 
I'll try and make some PR's when I have time but as I also went ahead and made changes so the api functionality can be opt in through settings I'll need a couple of PRs to do that nicely. 
let me know when and how to sync up with you to push these through.

**Comment by BuddhiAbeyratneAL** [comment]
Using stripe you can indeed have a 0buck subscription 
people use these to identity verity 
Also to get payment details when making base subscriptions

**Comment by oscarychen** [comment]
> Using stripe you can indeed have a 0buck subscription
@BuddhiAbeyratne the 0 amount is fine as is. it's `null` that's causing issues. When would a subscription have a price that is `null`?

> Stripe users can have multiple subscriptions according to api (Specially if you are using payment links) stripe doesn't have unicity

I think the package currently does support multiple subscription, but don't quote me on that since it's been a while since I worked on this.

> a user can buy a subscription without being on system

not sure what you meant by this, but if the Stripe has subscription data about a user that is not processed through this app, the Stripe should be automatically updating your Django instances through webhooks, and a user would be created automatically in your Django application along with their subscription data.

Yes, if you would can clean up your commits and make a PR I'll find some time to review and merge and then publish a new release. Thanks for
