### ISSUE TITLE
current_subscription_items isn't efficient on DB queries

### ISSUE THREAD

**Issue by joshuakoh1** [oscarychen/drf-stripe-subscription#8]
Probably should rework the query.
```
In [57]: len(connection.queries)
Out[57]: 31

In [58]: u.stripe_user.current_subscription_items
Out[58]: {<SubscriptionItem: SubscriptionItem object>}

In [59]: len(connection.queries)
Out[59]: 39
```

**Comment by oscarychen** [comment]
Yes, this [line](https://github.com/oscarychen/drf-stripe-subscription/blob/9737f732c30f2432a5e69e33c23223524ba52127/drf_stripe/models.py#L26) should just be a Django query filter instead of a set comprehension in Python.

Edit: the problem actually stems from the `subscription_items` query. It's an easy enough fix, ill update all these custom properties on StripeUser and push a fix.
